law = Category.create(category_index: 1, name: 'Law')
old_testament_narrative = Category.create(category_index: 2, name: 'Old Testament Narrative')
wisdom_literature = Category.create(category_index: 3, name: 'Wisdom Literature')
major_prophets = Category.create(category_index: 4, name: 'Major Prophets')
minor_prophets = Category.create(category_index: 5, name: 'Minor Prophets')
new_testament_narrative = Category.create(category_index: 6, name: 'New Testament Narrative')
pauline_epistles = Category.create(category_index: 7, name: 'Pauline Epistles')
general_epistles = Category.create(category_index: 8, name: 'General Epistles')
apocalyptic_epistle = Category.create(category_index: 9, name: 'Apocalyptic Epistle')

Book.create(book_index: 1, full_name: 'The First Book of Moses Called Genesis', name: 'Genesis', chapters: 50, verses: 1533, category_id: law.id)
Book.create(book_index: 2, full_name: 'The Second Book of Moses Called Exodus', name: 'Exodus', chapters: 40, verses: 1213, category_id: law.id)
Book.create(book_index: 3, full_name: 'The Third Book of Moses Called Leviticus', name: 'Leviticus', chapters: 27, verses: 859, category_id: law.id)
Book.create(book_index: 4, full_name: 'The Fourth Book of Moses Called Numbers', name: 'Numbers', chapters: 36, verses: 1288, category_id: law.id)
Book.create(book_index: 5, full_name: 'The Fifth Book of Moses Called Deuteronomy', name: 'Deuteronomy', chapters: 34, verses: 959, category_id: law.id)
Book.create(book_index: 6, full_name: 'The Book of Joshua', name: 'Joshua', chapters: 24, verses: 658, category_id: old_testament_narrative.id)
Book.create(book_index: 7, full_name: 'The Book of Judges', name: 'Judges', chapters: 21, verses: 618, category_id: old_testament_narrative.id)
Book.create(book_index: 8, full_name: 'The Book of Ruth', name: 'Ruth', chapters: 4, verses: 85, category_id: old_testament_narrative.id)
Book.create(book_index: 9, full_name: 'The First Book of Samuel', name: '1-Samuel', chapters: 31, verses: 810, category_id: old_testament_narrative.id)
Book.create(book_index: 10, full_name: 'The Second Book of Samuel', name: '2-Samuel', chapters: 24, verses: 695, category_id: old_testament_narrative.id)
Book.create(book_index: 11, full_name: 'The First Book of Kings', name: '1-Kings', chapters: 22, verses: 816, category_id: old_testament_narrative.id)
Book.create(book_index: 12, full_name: 'The Second Book of Kings', name: '2-Kings', chapters: 25, verses: 719, category_id: old_testament_narrative.id)
Book.create(book_index: 13, full_name: 'The First Book of Chronicles', name: '1-Chronicles', chapters: 29, verses: 942, category_id: old_testament_narrative.id)
Book.create(book_index: 14, full_name: 'The Second Book of Chronicles', name: '2-Chronicles', chapters: 36, verses: 822, category_id: old_testament_narrative.id)
Book.create(book_index: 15, full_name: 'The Book of Ezra', name: 'Ezra', chapters: 10, verses: 280, category_id: old_testament_narrative.id)
Book.create(book_index: 16, full_name: 'The Book of Nehemiah', name: 'Nehemiah', chapters: 13, verses: 406, category_id: old_testament_narrative.id)
Book.create(book_index: 17, full_name: 'The Book of Esther', name: 'Esther', chapters: 10, verses: 167, category_id: old_testament_narrative.id)
Book.create(book_index: 18, full_name: 'The Book of Job', name: 'Job', chapters: 42, verses: 1070, category_id: wisdom_literature.id)
Book.create(book_index: 19, full_name: 'The Book of Psalms', name: 'Psalms', chapters: 150, verses: 2461, category_id: wisdom_literature.id)
Book.create(book_index: 20, full_name: 'The Book of Proverbs', name: 'Proverbs', chapters: 31, verses: 915, category_id: wisdom_literature.id)
Book.create(book_index: 21, full_name: 'The Book of Ecclesiastes', name: 'Ecclesiastes', chapters: 12, verses: 222, category_id: wisdom_literature.id)
Book.create(book_index: 22, full_name: 'The Song of Songs (or Song of Solomon or Canticles)', name: 'Song-of-Solomon', chapters: 8, verses: 117, category_id: wisdom_literature.id)
Book.create(book_index: 23, full_name: 'The Book of Isaiah', name: 'Isaiah', chapters: 66, verses: 1292, category_id: major_prophets.id)
Book.create(book_index: 24, full_name: 'The Book of Jeremiah', name: 'Jeremiah', chapters: 52, verses: 1364, category_id: major_prophets.id)
Book.create(book_index: 25, full_name: 'The Book of Lamentations', name: 'Lamentations', chapters: 5, verses: 154, category_id: major_prophets.id)
Book.create(book_index: 26, full_name: 'The Book of Ezekiel', name: 'Ezekiel', chapters: 48, verses: 1273, category_id: major_prophets.id)
Book.create(book_index: 27, full_name: 'The Book of Daniel', name: 'Daniel', chapters: 12, verses: 357, category_id: major_prophets.id)
Book.create(book_index: 28, full_name: 'The Book of Hosea', name: 'Hosea', chapters: 14, verses: 197, category_id: minor_prophets.id)
Book.create(book_index: 29, full_name: 'The Book of Joel', name: 'Joel', chapters: 3, verses: 73, category_id: minor_prophets.id)
Book.create(book_index: 30, full_name: 'The Book of Amos', name: 'Amos', chapters: 9, verses: 146, category_id: minor_prophets.id)
Book.create(book_index: 31, full_name: 'The Book of Obadiah', name: 'Obadiah', chapters: 1, verses: 21, category_id: minor_prophets.id)
Book.create(book_index: 32, full_name: 'The Book of Jonah', name: 'Jonah', chapters: 4, verses: 48, category_id: minor_prophets.id)
Book.create(book_index: 33, full_name: 'The Book of Micah', name: 'Micah', chapters: 7, verses: 105, category_id: minor_prophets.id)
Book.create(book_index: 34, full_name: 'The Book of Nahum', name: 'Nahum', chapters: 3, verses: 47, category_id: minor_prophets.id)
Book.create(book_index: 35, full_name: 'The Book of Habakkuk', name: 'Habakkuk', chapters: 3, verses: 56, category_id: minor_prophets.id)
Book.create(book_index: 36, full_name: 'The Book of Zephaniah', name: 'Zephaniah', chapters: 3, verses: 53, category_id: minor_prophets.id)
Book.create(book_index: 37, full_name: 'The Book of Haggai', name: 'Haggai', chapters: 2, verses: 38, category_id: minor_prophets.id)
Book.create(book_index: 38, full_name: 'The Book of Zechariah', name: 'Zechariah', chapters: 14, verses: 211, category_id: minor_prophets.id)
Book.create(book_index: 39, full_name: 'The Book of Malachi', name: 'Malachi', chapters: 4, verses: 55, category_id: minor_prophets.id)
Book.create(book_index: 40, full_name: 'The Gospel According to Matthew', name: 'Matthew', chapters: 28, verses: 1071, category_id: new_testament_narrative.id)
Book.create(book_index: 41, full_name: 'The Gospel According to Mark', name: 'Mark', chapters: 16, verses: 678, category_id: new_testament_narrative.id)
Book.create(book_index: 42, full_name: 'The Gospel According to Luke', name: 'Luke', chapters: 24, verses: 1151, category_id: new_testament_narrative.id)
Book.create(book_index: 43, full_name: 'The Gospel According to John', name: 'John', chapters: 21, verses: 879, category_id: new_testament_narrative.id)
Book.create(book_index: 44, full_name: 'The Acts of the Apostles', name: 'Acts', chapters: 28, verses: 1007, category_id: new_testament_narrative.id)
Book.create(book_index: 45, full_name: 'The Epistle of Paul to the Romans', name: 'Romans', chapters: 16, verses: 433, category_id: pauline_epistles.id)
Book.create(book_index: 46, full_name: 'The First Epistle of Paul to the Corinthians', name: '1-Corinthians', chapters: 16, verses: 437, category_id: pauline_epistles.id)
Book.create(book_index: 47, full_name: 'The Second Epistle of Paul to the Corinthians', name: '2-Corinthians', chapters: 13, verses: 257, category_id: pauline_epistles.id)
Book.create(book_index: 48, full_name: 'The Epistle of Paul to the Galatians', name: 'Galatians', chapters: 6, verses: 149, category_id: pauline_epistles.id)
Book.create(book_index: 49, full_name: 'The Epistle of Paul to the Ephesians', name: 'Ephesians', chapters: 6, verses: 155, category_id: pauline_epistles.id)
Book.create(book_index: 50, full_name: 'The Epistle of Paul to the Philippians', name: 'Philippians', chapters: 4, verses: 104, category_id: pauline_epistles.id)
Book.create(book_index: 51, full_name: 'The Epistle of Paul to the Colossians', name: 'Colossians', chapters: 4, verses: 95, category_id: pauline_epistles.id)
Book.create(book_index: 52, full_name: 'The First Epistle of Paul to the Thessalonians', name: '1-Thessalonians', chapters: 5, verses: 89, category_id: pauline_epistles.id)
Book.create(book_index: 53, full_name: 'The Second Epistle of Paul to the Thessalonians', name: '2-Thessalonians', chapters: 3, verses: 47, category_id: pauline_epistles.id)
Book.create(book_index: 54, full_name: 'The First Epistle of Paul to Timothy', name: '1-Timothy', chapters: 6, verses: 113, category_id: pauline_epistles.id)
Book.create(book_index: 55, full_name: 'The Second Epistle of Paul to Timothy', name: '2-Timothy', chapters: 4, verses: 83, category_id: pauline_epistles.id)
Book.create(book_index: 56, full_name: 'The Epistle of Paul to Titus', name: 'Titus', chapters: 3, verses: 46, category_id: pauline_epistles.id)
Book.create(book_index: 57, full_name: 'The Epistle of Paul to Philemon', name: 'Philemon', chapters: 1, verses: 25, category_id: pauline_epistles.id)
Book.create(book_index: 58, full_name: 'The Epistle to the Hebrews', name: 'Hebrews', chapters: 13, verses: 303, category_id: general_epistles.id)
Book.create(book_index: 59, full_name: 'The General Epistle of James', name: 'James', chapters: 5, verses: 108, category_id: general_epistles.id)
Book.create(book_index: 60, full_name: 'The First Epistle of Peter', name: '1-Peter', chapters: 5, verses: 105, category_id: general_epistles.id)
Book.create(book_index: 61, full_name: 'The Second Epistle of Peter', name: '2-Peter', chapters: 3, verses: 61, category_id: general_epistles.id)
Book.create(book_index: 62, full_name: 'The First Epistle of John', name: '1-John', chapters: 5, verses: 105, category_id: general_epistles.id)
Book.create(book_index: 63, full_name: 'The Second Epistle of John', name: '2-John', chapters: 1, verses: 13, category_id: general_epistles.id)
Book.create(book_index: 64, full_name: 'The Third Epistle of John', name: '3-John', chapters: 1, verses: 14, category_id: general_epistles.id)
Book.create(book_index: 65, full_name: 'The Epistle of Jude', name: 'Jude', chapters: 1, verses: 25, category_id: general_epistles.id)
Book.create(book_index: 66, full_name: 'The Book of Revelation (or The Apocalypse of John)', name: 'Revelation', chapters: 22, verses: 404, category_id: apocalyptic_epistle.id)